2020/04/18 14:03:45 [error] 4110#4110: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: local.cc, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "local.cc"
2020/04/18 14:03:47 [error] 4110#4110: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: local.cc, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "local.cc"
2020/04/18 14:03:48 [error] 4110#4110: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: local.cc, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "local.cc"
2020/04/18 14:03:49 [error] 4110#4110: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: local.cc, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "local.cc"
2020/04/18 14:03:51 [error] 4110#4110: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: local.cc, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "local.cc"
2020/04/18 14:04:15 [error] 4110#4110: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: local.cc, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "local.cc"
